### ISSUE TITLE
Add option to toggle wrapping

### ISSUE THREAD

**Issue by Keith94** [jmmerz/move-tab-hotkeys#1]
Some users may want to disable the wrapping when moving tabs left/right, also I think Firefox's native shortcuts for moving tabs (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Page Up</kbd>/<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Page Down</kbd>) don't use wrapping.

**Comment by jmmerz** [comment]
Thanks for the suggestion! That makes sense and will give me an excuse to build in some configuration. I'll try to get that in the next week or two.

**Comment by Keith94** [comment]
Thanks for consideration. 👍
