### ISSUE TITLE
Add customizable shortcuts

### ISSUE THREAD

**Issue by Keith94** [jmmerz/move-tab-hotkeys#2]
Is there any way we can have fully customizable shortcuts yet?

**Comment by jmmerz** [comment]
It looks like this is unfortunately not available yet: Two relevant bugzilla bugs:

- https://bugzilla.mozilla.org/show_bug.cgi?id=1303384
- https://bugzilla.mozilla.org/show_bug.cgi?id=1320332

It's not clear from those if/when it will happen :(

**Comment by Keith94** [comment]
I see, only choice is to wait for support to be added. :-(
Please keep us updated if something changes.

**Comment by jmmerz** [comment]
Finally got around to building this. Apologies for the months-long delay. Please let me know if you run into any troubles with the key selectors.

**Comment by Keith94** [comment]
So far so good. Thanks for the great work man!
